app/models/prediction.py
import logging
from enum import Enum

from flask import url_for
from sqlalchemy import event
from sqlalchemy.orm import relationship
from sqlalchemy.orm.exc import NoResultFound

from app.db import db
from app.models import BaseModel, CustomerActionModel, Actions


class TaskStatusTypes(Enum):
    queued = 'QUEUED'
    started = 'STARTED'
    successful = 'SUCCESSFUL'
    failed = 'FAILED'


class PredictionTaskModel(BaseModel):
    __tablename__ = 'prediction_task'

    INCLUDE_ATTRIBUTES = ('status', 'statuses', 'result')

    name = db.Column(db.String(60), nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    user = relationship('UserModel', back_populates='tasks')

    task_code = db.Column(db.String(60), unique=True, nullable=False)
    statuses = relationship('TaskStatusModel')

    datasource_id = db.Column(db.Integer, db.ForeignKey('data_source.id'), nullable=False)
    datasource = relationship('DataSourceModel', back_populates='prediction_task_list')

    prediction_result = relationship('PredictionResultModel', uselist=False, back_populates='prediction_task')
    prediction_request = db.Column(db.JSON)

    @staticmethod
    def get_by_task_code(task_code):
        try:
            return PredictionTaskModel.query.filter(PredictionTaskModel.task_code == task_code).one()
        except NoResultFound:
            return None

    @staticmethod
    def get_by_user_id(user_id):
        return PredictionTaskModel.query.filter(PredictionTaskModel.user_id == user_id).all()

    @property
    def status(self):
        if len(self.statuses):
            return self.statuses[-1].state
        return None

    @property
    def result(self):
        logging.warning(self.status)
        if self.status in [TaskStatusTypes.successful.value, TaskStatusTypes.failed.value]:
            return url_for('prediction.result', task_code=self.task_code, _external=True)
        return None


class TaskStatusModel(BaseModel):
    __tablename__ = 'task_status'

    prediction_task_id = db.Column(db.Integer, db.ForeignKey('prediction_task.id'), nullable=False)
    prediction_task = relationship('PredictionTaskModel', back_populates='statuses')
    state = db.Column(db.String(10), index=True)
    message = db.Column(db.JSON, nullable=True)


class PredictionResultModel(BaseModel):
    __tablename__ = 'prediction_result'

    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    user = relationship('UserModel', back_populates='results')
    task_code = db.Column(db.String(60), unique=True)
    result = db.Column(db.JSON)

    prediction_task_id = db.Column(db.Integer, db.ForeignKey('prediction_task.id'), nullable=False)
    prediction_task = relationship('PredictionTaskModel', back_populates='prediction_result')

    @staticmethod
    def get_for_task(task_code):
        try:
            return PredictionResultModel.query.filter(PredictionResultModel.task_code == task_code).one()
        except NoResultFound:
            return None

    def to_dict(self):
        dictionary = super(PredictionResultModel, self).to_dict()
        dictionary['prediction_task'] = self.prediction_task
        return dictionary


def update_user_action(mapper, connection, self):
    session = db.create_scoped_session()
    action = CustomerActionModel(
        user_id=self.user_id,
        action=Actions.PREDICTION_STARTED
    )
    session.add(action)
    session.commit()


event.listen(PredictionTaskModel, 'after_insert', update_user_action)

app/views/customer.py
import logging
import os
from datetime import timedelta, datetime

import pandas as pd
from flask import (
    Blueprint, jsonify, render_template, g, request, abort, Response,
    flash, redirect, url_for, current_app
)

from app import services, ApiResponse
from app.core.auth import requires_access_token
from app.core.models import DataSource
from app.core.utils import handle_error, allowed_extension, generate_upload_code
from app.entities import CompanyConfigurationEntity, PredictionTaskEntity
from app.entities.datasource import UploadTypes
from app.interpreters.prediction import (
    prediction_result_to_dataframe_with_error,
    calculate_average_factors_percentage,
    combine_average_and_symbols_sensitivities)
from config import MAXIMUM_DAYS_FORECAST, DATETIME_FORMAT, DEFAULT_TIME_RESOLUTION

customer_blueprint = Blueprint('customer', __name__)


@customer_blueprint.route('/dashboard')
@requires_access_token
def dashboard():
    company = g.user.company
    prediction_tasks = services.prediction.get_tasks_by_company_id(g.user.company.id)

    context = {
        'user_id': g.user.id,
        'profile': {'email': g.user.email},
        'datasource': company.current_datasource,
        'prediction_task_list': prediction_tasks,
    }

    return render_template('dashboard.html', **context)


@customer_blueprint.route('/datasource', methods=['GET'])
@requires_access_token
def list_datasources():
    company = g.user.company
    current_datasource = company.current_datasource
    prediction_task_list = getattr(current_datasource, 'prediction_task_list', [])

    context = {
        'user_id': g.user.id,
        'profile': {'email': g.user.email},
        'current_datasource': current_datasource,
        'datasource_history': company.data_sources,
        'prediction_task_list': prediction_task_list
    }

    return render_template('datasource/list.html', **context)


@customer_blueprint.route('/datasource/template')
@requires_access_token
def get_company_datasource_template():
    csv_interpreter = services.company.get_datasource_interpreter(g.user.company.current_configuration)
    columns = [csv_interpreter.INDEX_COLUMN] + csv_interpreter.COLUMNS

    return Response(
        pd.DataFrame(columns=columns).to_csv(header=True, index=False),
        mimetype='text/csv',
        headers={"Content-disposition": f"attachment; filename={g.user.company.name}_template.csv"}
    )


@customer_blueprint.route('/datasource/<string:datasource_id>', methods=['GET'])
@requires_access_token
def view_datasource(datasource_id):
    datasource = services.datasource.get_by_upload_code(upload_code=datasource_id)
    if not datasource:
        return handle_error(404, "No such datasource!")
    if not datasource.company_id == g.user.company_id:
        return handle_error(403, "Unauthorised")
    context = {
        'current_datasource': datasource,
        'profile': {'email': g.user.email},
        'prediction_task_list': services.prediction.get_task_for_datasource_id(datasource.id)
    }

    return render_template('datasource/detail.html', **context)


@customer_blueprint.route('/prediction/new', methods=['GET'])
@requires_access_token
def new_prediction():
    company = g.user.company
    current_datasource = company.current_datasource
    if not current_datasource:
        logging.debug(
            f"Asked to create a prediction when no data source was available for company {g.user.company.name}")
        message = f"No data source available. <a href='{url_for('customer.list_datasources')}'>Upload one</a> first!"
        return handle_error(400, message)

    datasource_min_date = current_datasource.end_date
    max_date = datasource_min_date + timedelta(days=MAXIMUM_DAYS_FORECAST)

    context = {
        'user_id': g.user.id,
        'profile': {'email': g.user.email},
        'datasource': current_datasource,
        'datasource_end_date': datasource_min_date,
        'target_feature': company.current_configuration.configuration.target_feature,
        'min_date': datasource_min_date + timedelta(days=1),
        'max_date': max_date
    }

    return render_template('prediction/new.html', **context)


@customer_blueprint.route('/prediction/<string:task_code>')
@requires_access_token
def view_prediction(task_code):
    prediction = services.prediction.get_task_by_code(task_code)
    if not prediction:
        return handle_error(404, "No prediction found!")
    if not prediction.company_id == g.user.company_id:
        return handle_error(403, "Unauthorised")

    datasource = services.datasource.get_by_upload_code(prediction.datasource_upload_code)
    prediction.datasource = datasource

    if prediction.is_completed:
        elapsed = prediction.statuses[-1].last_update - prediction.created_at
    else:
        elapsed = datetime.utcnow() - prediction.created_at

    minutes, seconds = divmod(elapsed.seconds + elapsed.days * 86400, 60)
    hours, minutes = divmod(minutes, 60)

    context = {
        'user_id': g.user.id,
        'profile': {'email': g.user.email},
        'datasource': g.user.company.current_datasource,
        'prediction': prediction,
        'elapsed': f"{hours:02d}:{minutes:02d}:{seconds:02d}",
        'result': None
    }

    result_dataframe = prediction_result_to_dataframe_with_error(prediction)
    if result_dataframe is not None:

        latest_date_in_datasource = g.user.company.current_datasource.end_date.date()
        latest_date_in_results = result_dataframe.index[-1].date()

        headers = list(result_dataframe.columns)
        target_feature = g.user.company.current_configuration.configuration.target_feature

        if latest_date_in_datasource > latest_date_in_results:
            actuals_dataframe = services.datasource.get_dataframe(g.user.company.current_datasource)
            actuals_dataframe.index = actuals_dataframe.index.tz_localize('UTC')
            actuals_dataframe = actuals_dataframe.resample(DEFAULT_TIME_RESOLUTION).sum()
            result_dataframe['actuals'] = actuals_dataframe[target_feature]
            result_dataframe['actuals'] = result_dataframe['actuals'].transform(
                lambda x: "{:.2f};{:.2f};{:.2f}".format(x, x, x)
            )
            headers.append('actuals')

        factors = prediction.prediction_result.result['factors']

        percent_factors = calculate_average_factors_percentage(factors)
        context['result'] = {
            'data': prediction.prediction_result.result['datapoints'][0]['prediction'],
            'header': headers,
            'target_feature': target_feature,
            'timestamp_range': [
                result_dataframe.index[0].strftime(DATETIME_FORMAT),
                result_dataframe.index[-1].strftime(DATETIME_FORMAT)
            ],
            'status': prediction.statuses[-1].state,
            'prediction_result': prediction.prediction_result,
            'factors': percent_factors
        }

    return render_template('prediction/view.html', **context)


@customer_blueprint.route('/prediction/<string:task_code>/download')
@requires_access_token
def download_prediction_csv(task_code):
    prediction = PredictionTaskEntity.get_by_task_code(task_code)
    if not prediction:
        return handle_error(404, "No prediction found!")

    if not prediction.company_id == g.user.company_id:
        return handle_error(403, "Unauthorised")

    result_dataframe = prediction_result_to_dataframe_with_error(prediction)

    return Response(
        result_dataframe.to_csv(),
        mimetype='text/csv',
        headers={"Content-disposition": "attachment; filename={}.csv".format(
            prediction.name
        )})


@customer_blueprint.route('/prediction/<string:task_code>/factors')
@requires_access_token
def download_prediction_factors(task_code):
    prediction = PredictionTaskEntity.get_by_task_code(task_code)
    if not prediction:
        return handle_error(404, "No prediction found!")

    if not prediction.company_id == g.user.company_id:
        return handle_error(403, "Unauthorised")

    factors = prediction.prediction_result.result['factors']
    prediction_factors = combine_average_and_symbols_sensitivities(factors)

    df = pd.DataFrame(prediction_factors)
    return Response(
        df.to_csv(index_label=['symbol']),
        mimetype='text/csv',
        headers={"Content-disposition": "attachment; filename={}_sensitivities.csv".format(
            prediction.name
        )})


@customer_blueprint.route('/prediction/predictions/download')
@requires_access_token
def download_all_predictions():

    current_user_company_id = g.user.company_id
    prediction_list = PredictionTaskEntity.get_successful_by_company_id(current_user_company_id)

    result_dataframe = pd.DataFrame()

    for prediction in prediction_list:
        current_df = prediction_result_to_dataframe_with_error(prediction)
        result_dataframe = pd.concat([result_dataframe, current_df])

    return Response(
        result_dataframe.sort_index().to_csv(),
        mimetype='text/csv',
        headers={"Content-disposition": "attachment; filename={}_bulk_predictions.csv".format(
                datetime.now().strftime('%Y%m%d%H%M%S')
        )})


@customer_blueprint.route('/prediction', methods=['GET'])
@requires_access_token
def list_predictions():
    prediction_tasks = services.prediction.get_tasks_by_company_id(g.user.company.id)

    context = {
        'user_id': g.user.id,
        'profile': {'email': g.user.email},
        'datasource': g.user.company.current_datasource,
        'prediction_task_list': prediction_tasks
    }

    return render_template("prediction/list.html", **context)


@customer_blueprint.route('/datasource', methods=['POST'])
@requires_access_token
def datasource_upload():
    user = g.user
    company = user.company

    if not len(request.files):
        logging.debug("No file was uploaded")
        return handle_error(400, "No file Provided!")

app/views/prediction.py
import logging

from flask import Blueprint, jsonify, url_for, g, request, abort

from app import services
from app.core.auth import requires_access_token
from app.core.content import ApiResponse
from app.core.schemas import PredictionRequestSchema
from app.core.utils import parse_request_data
from app.entities import TaskStatusTypes
from app.tasks.predict import training_and_prediction_task

predict_blueprint = Blueprint('prediction', __name__)


@predict_blueprint.route('/', methods=['POST'])
@requires_access_token
@parse_request_data
def submit():
    company_id = g.user.company.id

    # the user can only predict against the _latest_ datasource
    datasource_id = g.user.company.current_datasource.id
    prediction_request, errors = PredictionRequestSchema().load(g.json)
    if errors:
        return jsonify(errors=errors), 400

    task_code = services.prediction.generate_task_code()
    logging.warning("Generated task code was %s", task_code)

    prediction_task = services.prediction.create_prediction_task(
        task_name=prediction_request['name'],
        task_code=task_code,
        company_id=company_id,
        user_id=g.user.id,
        datasource_id=datasource_id,
    )

    services.prediction.set_task_status(prediction_task, TaskStatusTypes.queued)
    upload_code = g.user.company.current_datasource.upload_code
    training_and_prediction_task.apply_async(
        (task_code, company_id, upload_code, prediction_request)
    )

    response = ApiResponse(
        content_type=request.accept_mimetypes.best,
        next=url_for('customer.dashboard'),
        context={
            'task_code': task_code,
            'task_status': url_for('prediction.get_single_task', task_code=task_code, _external=True),
            'result': url_for('prediction.result', task_code=task_code, _external=True)
        }
    )

    return response()


@predict_blueprint.route('/', methods=['GET'])
@requires_access_token
def get_tasks():
    return jsonify(g.user.company.prediction_tasks)


@predict_blueprint.route('/<string:task_code>', methods=['GET'])
@requires_access_token
@parse_request_data
def get_single_task(task_code):
    prediction_task = services.prediction.get_task_by_code(task_code)
    if not prediction_task:
        logging.debug(f"No task found for code {task_code}")
        abort(404, 'No task found!')
    if not prediction_task.company_id == g.user.company_id:
        abort(403)

    response = ApiResponse(
        content_type=request.accept_mimetypes.best,
        context=prediction_task,
    )

    return response()


@predict_blueprint.route('/result', methods=['GET'])
@requires_access_token
@parse_request_data
def get_results():
    return jsonify(g.user.company.prediction_results)


@predict_blueprint.route('/result/<string:task_code>')
@requires_access_token
def result(task_code):
    """
    Get the result of an individual task
    """
    prediction_result = services.prediction.get_result_by_code(task_code)
    if not prediction_result:
        logging.debug(f"No result was found for task code {task_code}")
        abort(404, 'No result found!')

    response = ApiResponse(
        content_type=request.accept_mimetypes.best,
        context=prediction_result
    )

    return response()

app/templates/prediction/list.html
{% extends "layout/main.html" %}

{% set page_title %}List Prediction{% endset %}

{% block page_header %}
    <h1>
        Your Predictions
        <small>Here's the list of predictions</small>
    </h1>
{% endblock %}
{% block breadcrumb_items %}
    {{ super() }}
    <li><a class="active"><i class="fa fa-list"></i>Prediction List</a></li>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="box box-info">
                <h3 class="box-header with-border">Predictions</h3>
                <div class="box-body">
                    {% if datasource %}
                        {% if prediction_task_list %}
                            <p>
                                <a href="{{ url_for('customer.download_all_predictions') }}"><i class="fa fa-download"></i> Download all successful prediction results in one single file</a>
                            </p>
                        {% endif %}
                        {{ macros.print_task_list(prediction_task_list) }}
                    {% else %}
                        <div class="callout callout-warning">
                            <p>
                                Can't create a prediction with empty Historical Data. Please manage your data in the <a href='{{ url_for('customer.list_datasources') }}'>Historical data page</a>.
                            </p>
                        </div>
                    {%  endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/prediction/view.html
{% extends "layout/main.html" %}
{% set page_title %}List Prediction{% endset %}

{% block page_header %}
    <h1>
        Your Prediction: {{ prediction.name }}
        <small></small>
    </h1>
{% endblock %}
{% block breadcrumb_items %}
    {{ super() }}
    <li><a href="{{ url_for('customer.list_predictions') }}"><i class="fa fa-list"></i>Prediction List</a></li>
    <li><a class="active"><i class="fa fa-rocket"></i>Prediction</a></li>

{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-6">
            <div class="box box-success">
                <h3 class="box-header with-border">Prediction</h3>
                <div class="box-body">
                    <dl class="dl-horizontal">
                        <dt>Name:</dt>
                        <dd>{{ prediction.name }}</dd>
                        <dt>Created:</dt>
                        <dd>{{ macros.format_datetime(prediction.created_at) }}</dd>
                        <dt>Start Time:</dt>
                        <dd>{{ prediction.prediction_request['start_time'] }}</dd>
                    </dl>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="box box-success">
                <h3 class="box-header with-border">Associated Historical Data</h3>
                <div class="box-body">
                    {{ macros.print_datasource_info(prediction.datasource) }}
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="box">
                <h3 class="box-header with-border">Status log</h3>
                <div class="box-body">
                    <table class="table table-bordered prediction-log" id="{{ prediction.task_code }}"
                           data-completed="{{ prediction.is_completed }}">
                        <thead>
                        <tr>
                            <th>created</th>
                            <th>status</th>
                            <th>message</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for status in prediction.statuses %}

                            <tr>
                                <td>{{ macros.format_datetime(status.created_at) }}</td>
                                <td>{{ status.state }}</td>
                                <td>{{ status.message }}</td>
                            </tr>
                        {% endfor %}
                        <tfoot>
                        <tr>
                            <td colspan="4" class="text-right text-green text-bold">
                                {% if not prediction.is_completed %}
                                    <i id="status-spinner" class="fa fa-refresh fa-spin"></i> &nbsp;&nbsp;
                                {% endif %}
                                Elapsed time: <span id="elapsed-prediction-time">
                                           {{ elapsed }}
                                        </span>
                            </td>
                        </tr>

                        </tr>
                        </tfoot>

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    {% if result %}
        <div class="row">
            <div class="col-md-12">
                <div class="box">
                    <h3 class="box-header with-border">Result</h3>
                    <div class="box-body">
                        {% if result.status == 'SUCCESSFUL' %}
                            <div class="row">
                                <div class="col-md-12">
                                    <dl class="dl-horizontal">
                                        <dt>Feature Predicted</dt>
                                        <dd>{{ result.target_feature }}</dd>
                                        <dt>Date Range</dt>
                                        <dd>[ {{ result.timestamp_range[0] }} - {{ result.timestamp_range[1] }} ]</dd>
                                    </dl>
                                    <div class="row">
                                        <div class="col-xs-12">
                                            <canvas id="prediction-bars"></canvas>
                                            {{ header }}
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-xs-12">
                                            <strong>
                                                <a href="{{ url_for('customer.download_prediction_csv', task_code=prediction.task_code) }}"
                                                   target="_blank">
                                                    <i class="fa fa-download"></i>
                                                    Download the AI factors
                                                </a>
                                            </strong>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-xs-12">
                                            <strong>
                                                <a href="{{ url_for('customer.download_prediction_factors', task_code=prediction.task_code) }}"
                                                   target="_blank">
                                                    <i class="fa fa-download"></i>
                                                    Download the sensitivities
                                                </a>
                                            </strong>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-xs-6">
                                            <h3>Average sensitivities</h3>
                                            <table class="table">
                                                {% for key, value in result.factors.items() %}
                                                    <tr>
                                                        <th>{{ key }}</th>
                                                        <td>{{ value }}%</td>
                                                    </tr>
                                                {% endfor %}
                                            </table>
                                        </div>
                                        <div class="col-xs-6">
                                            <canvas id="sensitivies-pie"></canvas>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% else %}
                            <div class="row">
                                <div class="col-md-12">
                                    {% if prediction_status in ['QUEUED', 'STARTED'] %}
                                        <div class="callout callout-info">
                                            <h4>Processing</h4>
                                            <p>
                                                Current status of the prediction is {{ prediction_status }}
                                                &nbsp;
                                                <a class="btn btn-primary" href=""><i class="fa fa-refresh"></i></a>
                                            </p>
                                        </div>
                                    {% elif prediction_status == 'FAILED' %}
                                        <div class="callout callout-danger">
                                            <h4>Failed</h4>
                                            <p>This prediction has failed so no result displayed</p>
                                        </div>
                                    {% endif %}
                                </div>

                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}


{% block footer_js %}
    {{ super() }}
    <script>
        $(document).ready(function ($) {
            {% if not prediction.is_completed %}
                setInterval(PredictionStatusRefresh.refreshStatuses, 1000);
            {% else %}
                {% if result %}
                {%  set prediction_result = [] %}
                {%  set upper_bounds = [] %}
                {%  set lower_bounds = [] %}
                {%  set prediction_labels = [] %}
                {%- for value in result.data -%}
                    {%- if value.value -%}
                        {%- do prediction_result.append(value.value) -%}
                        {%- do upper_bounds.append(value.upper) -%}
                        {%- do lower_bounds.append(value.lower) -%}
                        {%- do prediction_labels.append(value.symbol) -%}
                    {%- endif -%}
                {%- endfor -%}
                var prediction_data = {
                    datasets: [
                        {
                            data: [{%  for value in lower_bounds %}{{ value }}{% if not loop.last %}, {% endif %}{% endfor %}],
                            backgroundColor: ChartDecorator.getAlphaChartColors({{ lower_bounds|length }}),
                            label: '{{ result.target_feature|capitalize }} (16th percentile)'
                        },
                        {
                            data: [{%  for value in prediction_result %}{{ value }}{% if not loop.last %}, {% endif %}{% endfor %}],
                            backgroundColor: ChartDecorator.getChartColors({{ prediction_result|length }}),
                            label: '{{ result.target_feature|capitalize }}'
                        },
                        {
                            data: [{%  for value in upper_bounds %}{{ value }}{% if not loop.last %}, {% endif %}{% endfor %}],
                            backgroundColor: ChartDecorator.getAlphaChartColors({{ upper_bounds|length }}),
                            label: '{{ result.target_feature|capitalize }} (84th percentile)'
                        }
                    ],
                    labels: [{%  for value in prediction_labels %}'{{ value }}'{% if not loop.last %}, {% endif %}{% endfor %}]
                }

                var bar_canvas = document.getElementById('prediction-bars');
                new Chart(bar_canvas, {
                    type: 'bar',
                    data: prediction_data,
                    options: {
                        legend: {
                            position: 'top',
                            labels: {
                                fontSize: 14
                            }
                        },
                        title: {
                            text: 'AI Factors',
                            display: true,
                            fontSize: 16,
                            padding: 20
                        },
                        scales: {
                            xAxes: [{stacked: true}]
                        }

                    }
                });
                    var sensitivities_data = {
                        datasets: [{
                            data: [{% for key, value in result.factors.items()  %}{{ value }}{% if not loop.last %}, {% endif %}{% endfor %}],
                            backgroundColor: ChartDecorator.getChartColors({{ result.factors|length }})
                        }],
                        labels: [{% for key, value in result.factors.items()  %}'{{ key }}'{% if not loop.last %}, {% endif %}{% endfor %}],
                    };
                    var sensitivities_canvas = document.getElementById('sensitivies-pie');
                    new Chart(sensitivities_canvas, {
                        type: 'doughnut',
                        data: sensitivities_data,
                        options: {
                            legend: {
                                position: 'left',
                                labels: {
                                    fontSize: 14
                                }
                            },
                            title: {
                                text: 'Average factor sensitivities',
                                display: true,
                                fontSize: 16,
                                padding: 20
                            }
                        }
                    });
                {% endif %}


            {% endif %}
        });
    </script>
{% endblock %}