app/views/authentication.py
import datetime
import logging

from flask import Blueprint, g, url_for, request

from app import services
from app.core.auth import requires_access_token
from app.core.content import ApiResponse
from app.core.utils import parse_request_data, handle_error
from config import TOKEN_EXPIRATION

authentication_blueprint = Blueprint('authentication', __name__)


@authentication_blueprint.route('/login', methods=['POST'])
@parse_request_data
def login():
    email = g.json.get('email')
    password = g.json.get('password')

    user = services.user.get_by_email(email)
    if not user:
        logging.debug(f"No user found for {email}")
        return handle_error(401, 'Incorrect user or password')

    if not services.user.verify_password(user, password):
        logging.warning(f"Incorrect password for {email}")
        return handle_error(401, 'Incorrect user or password')

    if not user.confirmed:
        logging.warning(f"User {user.email} hasn't been confirmed!")
        return handle_error(401, f'Please confirm user {user.email} first')

    token = services.user.generate_auth_token(user, expiration=TOKEN_EXPIRATION)
    ascii_token = token.decode('ascii')

    response = ApiResponse(
        content_type=request.accept_mimetypes.best,
        next=url_for('customer.dashboard'),
        context={'token': ascii_token}
    )

    response.set_cookie(
        'token', ascii_token,
        expires=datetime.datetime.now() + datetime.timedelta(minutes=TOKEN_EXPIRATION)
    )

    return response()


@authentication_blueprint.route('/logout')
@requires_access_token
def logout():
    response = ApiResponse(
        content_type=request.accept_mimetypes.best,
        next=url_for('main.login')
    )
    response.set_cookie('token', '', expires=0)

    return response()

app/views/customer.py
import logging
import os
from datetime import timedelta, datetime

import pandas as pd
from flask import (
    Blueprint, jsonify, render_template, g, request, abort, Response,
    flash, redirect, url_for, current_app
)

from app import services, ApiResponse
from app.core.auth import requires_access_token
from app.core.models import DataSource
from app.core.utils import handle_error, allowed_extension, generate_upload_code
from app.entities import CompanyConfigurationEntity, PredictionTaskEntity
from app.entities.datasource import UploadTypes
from app.interpreters.prediction import (
    prediction_result_to_dataframe_with_error,
    calculate_average_factors_percentage,
    combine_average_and_symbols_sensitivities)
from config import MAXIMUM_DAYS_FORECAST, DATETIME_FORMAT, DEFAULT_TIME_RESOLUTION

customer_blueprint = Blueprint('customer', __name__)


@customer_blueprint.route('/dashboard')
@requires_access_token
def dashboard():
    company = g.user.company
    prediction_tasks = services.prediction.get_tasks_by_company_id(g.user.company.id)

    context = {
        'user_id': g.user.id,
        'profile': {'email': g.user.email},
        'datasource': company.current_datasource,
        'prediction_task_list': prediction_tasks,
    }

    return render_template('dashboard.html', **context)


@customer_blueprint.route('/datasource', methods=['GET'])
@requires_access_token
def list_datasources():
    company = g.user.company
    current_datasource = company.current_datasource
    prediction_task_list = getattr(current_datasource, 'prediction_task_list', [])

    context = {
        'user_id': g.user.id,
        'profile': {'email': g.user.email},
        'current_datasource': current_datasource,
        'datasource_history': company.data_sources,
        'prediction_task_list': prediction_task_list
    }

    return render_template('datasource/list.html', **context)


@customer_blueprint.route('/datasource/template')
@requires_access_token
def get_company_datasource_template():
    csv_interpreter = services.company.get_datasource_interpreter(g.user.company.current_configuration)
    columns = [csv_interpreter.INDEX_COLUMN] + csv_interpreter.COLUMNS

    return Response(
        pd.DataFrame(columns=columns).to_csv(header=True, index=False),
        mimetype='text/csv',
        headers={"Content-disposition": f"attachment; filename={g.user.company.name}_template.csv"}
    )


@customer_blueprint.route('/datasource/<string:datasource_id>', methods=['GET'])
@requires_access_token
def view_datasource(datasource_id):
    datasource = services.datasource.get_by_upload_code(upload_code=datasource_id)
    if not datasource:
        return handle_error(404, "No such datasource!")
    if not datasource.company_id == g.user.company_id:
        return handle_error(403, "Unauthorised")
    context = {
        'current_datasource': datasource,
        'profile': {'email': g.user.email},
        'prediction_task_list': services.prediction.get_task_for_datasource_id(datasource.id)
    }

    return render_template('datasource/detail.html', **context)


@customer_blueprint.route('/prediction/new', methods=['GET'])
@requires_access_token
def new_prediction():
    company = g.user.company
    current_datasource = company.current_datasource
    if not current_datasource:
        logging.debug(
            f"Asked to create a prediction when no data source was available for company {g.user.company.name}")
        message = f"No data source available. <a href='{url_for('customer.list_datasources')}'>Upload one</a> first!"
        return handle_error(400, message)

    datasource_min_date = current_datasource.end_date
    max_date = datasource_min_date + timedelta(days=MAXIMUM_DAYS_FORECAST)

    context = {
        'user_id': g.user.id,
        'profile': {'email': g.user.email},
        'datasource': current_datasource,
        'datasource_end_date': datasource_min_date,
        'target_feature': company.current_configuration.configuration.target_feature,
        'min_date': datasource_min_date + timedelta(days=1),
        'max_date': max_date
    }

    return render_template('prediction/new.html', **context)


@customer_blueprint.route('/prediction/<string:task_code>')
@requires_access_token
def view_prediction(task_code):
    prediction = services.prediction.get_task_by_code(task_code)
    if not prediction:
        return handle_error(404, "No prediction found!")
    if not prediction.company_id == g.user.company_id:
        return handle_error(403, "Unauthorised")

    datasource = services.datasource.get_by_upload_code(prediction.datasource_upload_code)
    prediction.datasource = datasource

    if prediction.is_completed:
        elapsed = prediction.statuses[-1].last_update - prediction.created_at
    else:
        elapsed = datetime.utcnow() - prediction.created_at

    minutes, seconds = divmod(elapsed.seconds + elapsed.days * 86400, 60)
    hours, minutes = divmod(minutes, 60)

    context = {
        'user_id': g.user.id,
        'profile': {'email': g.user.email},
        'datasource': g.user.company.current_datasource,
        'prediction': prediction,
        'elapsed': f"{hours:02d}:{minutes:02d}:{seconds:02d}",
        'result': None
    }

    result_dataframe = prediction_result_to_dataframe_with_error(prediction)
    if result_dataframe is not None:

        latest_date_in_datasource = g.user.company.current_datasource.end_date.date()
        latest_date_in_results = result_dataframe.index[-1].date()

        headers = list(result_dataframe.columns)
        target_feature = g.user.company.current_configuration.configuration.target_feature

        if latest_date_in_datasource > latest_date_in_results:
            actuals_dataframe = services.datasource.get_dataframe(g.user.company.current_datasource)
            actuals_dataframe.index = actuals_dataframe.index.tz_localize('UTC')
            actuals_dataframe = actuals_dataframe.resample(DEFAULT_TIME_RESOLUTION).sum()
            result_dataframe['actuals'] = actuals_dataframe[target_feature]
            result_dataframe['actuals'] = result_dataframe['actuals'].transform(
                lambda x: "{:.2f};{:.2f};{:.2f}".format(x, x, x)
            )
            headers.append('actuals')

        factors = prediction.prediction_result.result['factors']

        percent_factors = calculate_average_factors_percentage(factors)
        context['result'] = {
            'data': prediction.prediction_result.result['datapoints'][0]['prediction'],
            'header': headers,
            'target_feature': target_feature,
            'timestamp_range': [
                result_dataframe.index[0].strftime(DATETIME_FORMAT),
                result_dataframe.index[-1].strftime(DATETIME_FORMAT)
            ],
            'status': prediction.statuses[-1].state,
            'prediction_result': prediction.prediction_result,
            'factors': percent_factors
        }

    return render_template('prediction/view.html', **context)


@customer_blueprint.route('/prediction/<string:task_code>/download')
@requires_access_token
def download_prediction_csv(task_code):
    prediction = PredictionTaskEntity.get_by_task_code(task_code)
    if not prediction:
        return handle_error(404, "No prediction found!")

    if not prediction.company_id == g.user.company_id:
        return handle_error(403, "Unauthorised")

    result_dataframe = prediction_result_to_dataframe_with_error(prediction)

    return Response(
        result_dataframe.to_csv(),
        mimetype='text/csv',
        headers={"Content-disposition": "attachment; filename={}.csv".format(
            prediction.name
        )})


@customer_blueprint.route('/prediction/<string:task_code>/factors')
@requires_access_token
def download_prediction_factors(task_code):
    prediction = PredictionTaskEntity.get_by_task_code(task_code)
    if not prediction:
        return handle_error(404, "No prediction found!")

    if not prediction.company_id == g.user.company_id:
        return handle_error(403, "Unauthorised")

    factors = prediction.prediction_result.result['factors']
    prediction_factors = combine_average_and_symbols_sensitivities(factors)

    df = pd.DataFrame(prediction_factors)
    return Response(
        df.to_csv(index_label=['symbol']),
        mimetype='text/csv',
        headers={"Content-disposition": "attachment; filename={}_sensitivities.csv".format(
            prediction.name
        )})


@customer_blueprint.route('/prediction/predictions/download')
@requires_access_token
def download_all_predictions():

    current_user_company_id = g.user.company_id
    prediction_list = PredictionTaskEntity.get_successful_by_company_id(current_user_company_id)

    result_dataframe = pd.DataFrame()

    for prediction in prediction_list:
        current_df = prediction_result_to_dataframe_with_error(prediction)
        result_dataframe = pd.concat([result_dataframe, current_df])

    return Response(
        result_dataframe.sort_index().to_csv(),
        mimetype='text/csv',
        headers={"Content-disposition": "attachment; filename={}_bulk_predictions.csv".format(
                datetime.now().strftime('%Y%m%d%H%M%S')
        )})


@customer_blueprint.route('/prediction', methods=['GET'])
@requires_access_token
def list_predictions():
    prediction_tasks = services.prediction.get_tasks_by_company_id(g.user.company.id)

    context = {
        'user_id': g.user.id,
        'profile': {'email': g.user.email},
        'datasource': g.user.company.current_datasource,
        'prediction_task_list': prediction_tasks
    }

    return render_template("prediction/list.html", **context)


@customer_blueprint.route('/datasource', methods=['POST'])
@requires_access_token
def datasource_upload():
    user = g.user
    company = user.company

    if not len(request.files):
        logging.debug("No file was uploaded")
        return handle_error(400, "No file Provided!")

app/templates/partial/datasource_upload.html
<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <h3 class="box-header with-border">Update data source</h3>
            <div class="box-body">
                <form action="/upload" method="post" enctype="multipart/form-data" class="form-inline">
                    <div class="form-group">
                        <div class="col-md-8">
                            <div class="input-group">
                                <input type="text" id="file_path" class="form-control" placeholder="Browse...">
                                <span class="input-group-btn">
                                    <button class="btn btn-default" type="button" id="file_browser">
                                    <i class="fa fa-search"></i> Browse</button>
                                </span>

                            </div>
                            <input type="file" class="hidden" name="upload" id="upload">
                        </div>
                        <div class="col-md-4">
                             <input class="btn btn-primary" type="submit" value="Upload file" name="submit">
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script>
    $('#file_browser').click(function(e){
        e.preventDefault();
        $('#upload').click();
    });

    $('#file').change(function(){
        $('#file_path').val($(this).val());
    });

    $('#file_path').click(function(){
        $('#file_browser').click();
    });
    </script>

app/templates/partial/footer_js.html
<!-- jQuery 3 -->
<script src="{{ url_for('static', filename='vendors/jquery/jquery.min.js') }}"></script>
<!-- Bootstrap 3.3.7 -->
<script src="{{ url_for('static', filename='vendors/bootstrap/js/bootstrap.min.js') }}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/js/bootstrap-select.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.1/js/bootstrap-datepicker.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.21.0/moment.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment-timezone/0.5.14/moment-timezone-with-data-2012-2022.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment-duration-format/2.2.2/moment-duration-format.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.min.js"></script>
<!-- AdminLTE App -->
<script src="{{ url_for('static', filename='js/adminlte.min.js') }} "></script>
<!-- iCheck -->
<script src="{{ url_for('static', filename='vendors/iCheck/icheck.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/alphai.js') }} "></script>

app/templates/partial/html_header.html
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>APS | {{ page_title|default('Prediction Service') }}</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <link rel="stylesheet" href="{{ url_for('static', filename='vendors/bootstrap/css/bootstrap.min.css') }}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/css/bootstrap-select.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.1/css/bootstrap-datepicker.min.css">

  <!-- Font Awesome -->
  <link rel="stylesheet" href="{{ url_for('static', filename='vendors/font-awesome/css/font-awesome.min.css') }}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="{{ url_for('static', filename='vendors/ionicons/css/ionicons.min.css') }}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{ url_for('static', filename='css/AdminLTE.min.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/spacing.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='vendors/iCheck/square/blue.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/alphai.css') }}">

  <script src="//cdnjs.cloudflare.com/ajax/libs/dygraph/2.1.0/dygraph.min.js"></script>
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/dygraph/2.1.0/dygraph.min.css" />

    <!-- AdminLTE Skins. We have chosen the skin-blue for this starter
        page. However, you can choose any other skin. Make sure you
        apply the skin class to the body tag so the changes take effect. -->
  <link rel="stylesheet" href="{{ url_for('static', filename='css/skins/skin-blue.min.css') }}">
  <link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon.ico') }}">
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

  <!-- Google Font -->
  <link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>

app/templates/partial/main_header.html
<!-- Main Header -->
  <header class="main-header">

    <!-- Logo -->
    <a href="{{ url_for('customer.dashboard') }}" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><img src="{{ url_for('static', filename='img/alpha-i-logo-small.png') }}" title="alpha-i"></span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><img src="{{ url_for('static', filename='img/alpha-i-logo.png') }}" title="alpha-i"></span>
    </a>

    <!-- Header Navbar -->

        <nav class="navbar navbar-static-top" role="navigation">
          <!-- Sidebar toggle button-->
          <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
          </a>
          <!-- Navbar Right Menu -->
          <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
              <!-- Messages: style can be found in dropdown.less-->
              <!-- User Account Menu -->
                 {%  if profile %}
                  <li class="dropdown user user-menu">
                    <!-- Menu Toggle Button -->
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                      <!-- hidden-xs hides the username on small devices so only the image appears. -->
                      <span class="hidden-xs">Welcome {{ profile.email }} </span>
                    </a>
                    <ul class="dropdown-menu">
                      <li class="user-header">
                        <p>{{ profile.user_name }} ( {{ profile.email }})</p>
                      </li>
                      <li class="user-footer">
                        <div class="pull-left">
                          <a href="{{ url_for('authentication.logout') }}" class="btn btn-default btn-flat">Sign out</a>
                        </div>
                      </li>
                    </ul>
                  </li>
                 {%  endif %}
            </ul>
          </div>
        </nav>

  </header>

app/templates/partial/main_sidebar.html
  <aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
      <!-- Sidebar Menu -->
      <ul class="sidebar-menu" data-widget="tree">
        <li class="header">Menu</li>
        <!-- Optionally, you can add icons to the links -->
        <li><a href="{{ url_for('customer.dashboard') }}"><i class="fa fa-dashboard"></i> <span>Dashboard</span></a></li>
        <li><a href="{{ url_for('customer.list_datasources') }}"><i class="fa fa-database"></i> <span>Historical Data</span></a></li>
        <li><a href="{{ url_for('customer.list_predictions') }}"><i class="fa fa-rocket"></i> <span>Predictions</span></a></li>
      </ul>
      <!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
  </aside>