app/models/datasource.py
from enum import Enum

import pandas as pd
from flask_sqlalchemy import event
from sqlalchemy.orm import relationship
from sqlalchemy.orm.exc import NoResultFound

from app.db import db
from app.models import BaseModel, CustomerActionModel, Actions

STORE_INDEX = 'data'


class UploadTypes(Enum):
    FILESYSTEM = 'filesystem'
    BLOBSTORE = 'blobstore'


class DataSourceModel(BaseModel):
    __tablename__ = 'data_source'

    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    user = relationship('UserModel', foreign_keys=user_id)
    company_id = db.Column(db.Integer, db.ForeignKey('company.id'), nullable=False)
    company = relationship('CompanyModel', foreign_keys=company_id)
    upload_code = db.Column(db.String(), index=True)
    type = db.Column(db.Enum(UploadTypes), index=True)
    location = db.Column(db.String(), index=True)
    filename = db.Column(db.String(), nullable=False)

    start_date = db.Column(db.DateTime, index=True, nullable=True)
    end_date = db.Column(db.DateTime, index=True, nullable=True)

    prediction_task_list = relationship('PredictionTaskModel', back_populates='datasource')

    def get_file(self):

        with pd.HDFStore(self.location) as hdf_store:
            dataframe = hdf_store[STORE_INDEX]
            return dataframe

    @staticmethod
    def get_for_user(user_id):
        return DataSourceModel.query.filter(DataSourceModel.user_id == str(user_id)).all()

    @staticmethod
    def get_by_upload_code(upload_code):
        try:
            return DataSourceModel.query.filter(DataSourceModel.upload_code == upload_code).one()
        except NoResultFound:
            return None

    @staticmethod
    def generate_filename(upload_code, original_filename):
        return f"{upload_code}_{original_filename}"

    def to_dict(self):
        model_dict = super(DataSourceModel, self).to_dict()
        model_dict.update({'type': self.type.name})
        return model_dict


def update_user_action(mapper, connection, self):
    session = db.create_scoped_session()
    action = CustomerActionModel(
        user_id=self.user_id,
        action=Actions.FILE_UPLOAD
    )
    session.add(action)
    session.commit()


event.listen(DataSourceModel, 'after_insert', update_user_action)

app/views/customer.py
import logging
import os
from datetime import timedelta, datetime

import pandas as pd
from flask import (
    Blueprint, jsonify, render_template, g, request, abort, Response,
    flash, redirect, url_for, current_app
)

from app import services, ApiResponse
from app.core.auth import requires_access_token
from app.core.models import DataSource
from app.core.utils import handle_error, allowed_extension, generate_upload_code
from app.entities import CompanyConfigurationEntity, PredictionTaskEntity
from app.entities.datasource import UploadTypes
from app.interpreters.prediction import (
    prediction_result_to_dataframe_with_error,
    calculate_average_factors_percentage,
    combine_average_and_symbols_sensitivities)
from config import MAXIMUM_DAYS_FORECAST, DATETIME_FORMAT, DEFAULT_TIME_RESOLUTION

customer_blueprint = Blueprint('customer', __name__)


@customer_blueprint.route('/dashboard')
@requires_access_token
def dashboard():
    company = g.user.company
    prediction_tasks = services.prediction.get_tasks_by_company_id(g.user.company.id)

    context = {
        'user_id': g.user.id,
        'profile': {'email': g.user.email},
        'datasource': company.current_datasource,
        'prediction_task_list': prediction_tasks,
    }

    return render_template('dashboard.html', **context)


@customer_blueprint.route('/datasource', methods=['GET'])
@requires_access_token
def list_datasources():
    company = g.user.company
    current_datasource = company.current_datasource
    prediction_task_list = getattr(current_datasource, 'prediction_task_list', [])

    context = {
        'user_id': g.user.id,
        'profile': {'email': g.user.email},
        'current_datasource': current_datasource,
        'datasource_history': company.data_sources,
        'prediction_task_list': prediction_task_list
    }

    return render_template('datasource/list.html', **context)


@customer_blueprint.route('/datasource/template')
@requires_access_token
def get_company_datasource_template():
    csv_interpreter = services.company.get_datasource_interpreter(g.user.company.current_configuration)
    columns = [csv_interpreter.INDEX_COLUMN] + csv_interpreter.COLUMNS

    return Response(
        pd.DataFrame(columns=columns).to_csv(header=True, index=False),
        mimetype='text/csv',
        headers={"Content-disposition": f"attachment; filename={g.user.company.name}_template.csv"}
    )


@customer_blueprint.route('/datasource/<string:datasource_id>', methods=['GET'])
@requires_access_token
def view_datasource(datasource_id):
    datasource = services.datasource.get_by_upload_code(upload_code=datasource_id)
    if not datasource:
        return handle_error(404, "No such datasource!")
    if not datasource.company_id == g.user.company_id:
        return handle_error(403, "Unauthorised")
    context = {
        'current_datasource': datasource,
        'profile': {'email': g.user.email},
        'prediction_task_list': services.prediction.get_task_for_datasource_id(datasource.id)
    }

    return render_template('datasource/detail.html', **context)


@customer_blueprint.route('/prediction/new', methods=['GET'])
@requires_access_token
def new_prediction():
    company = g.user.company
    current_datasource = company.current_datasource
    if not current_datasource:
        logging.debug(
            f"Asked to create a prediction when no data source was available for company {g.user.company.name}")
        message = f"No data source available. <a href='{url_for('customer.list_datasources')}'>Upload one</a> first!"
        return handle_error(400, message)

    datasource_min_date = current_datasource.end_date
    max_date = datasource_min_date + timedelta(days=MAXIMUM_DAYS_FORECAST)

    context = {
        'user_id': g.user.id,
        'profile': {'email': g.user.email},
        'datasource': current_datasource,
        'datasource_end_date': datasource_min_date,
        'target_feature': company.current_configuration.configuration.target_feature,
        'min_date': datasource_min_date + timedelta(days=1),
        'max_date': max_date
    }

    return render_template('prediction/new.html', **context)


@customer_blueprint.route('/prediction/<string:task_code>')
@requires_access_token
def view_prediction(task_code):
    prediction = services.prediction.get_task_by_code(task_code)
    if not prediction:
        return handle_error(404, "No prediction found!")
    if not prediction.company_id == g.user.company_id:
        return handle_error(403, "Unauthorised")

    datasource = services.datasource.get_by_upload_code(prediction.datasource_upload_code)
    prediction.datasource = datasource

    if prediction.is_completed:
        elapsed = prediction.statuses[-1].last_update - prediction.created_at
    else:
        elapsed = datetime.utcnow() - prediction.created_at

    minutes, seconds = divmod(elapsed.seconds + elapsed.days * 86400, 60)
    hours, minutes = divmod(minutes, 60)

    context = {
        'user_id': g.user.id,
        'profile': {'email': g.user.email},
        'datasource': g.user.company.current_datasource,
        'prediction': prediction,
        'elapsed': f"{hours:02d}:{minutes:02d}:{seconds:02d}",
        'result': None
    }

    result_dataframe = prediction_result_to_dataframe_with_error(prediction)
    if result_dataframe is not None:

        latest_date_in_datasource = g.user.company.current_datasource.end_date.date()
        latest_date_in_results = result_dataframe.index[-1].date()

        headers = list(result_dataframe.columns)
        target_feature = g.user.company.current_configuration.configuration.target_feature

        if latest_date_in_datasource > latest_date_in_results:
            actuals_dataframe = services.datasource.get_dataframe(g.user.company.current_datasource)
            actuals_dataframe.index = actuals_dataframe.index.tz_localize('UTC')
            actuals_dataframe = actuals_dataframe.resample(DEFAULT_TIME_RESOLUTION).sum()
            result_dataframe['actuals'] = actuals_dataframe[target_feature]
            result_dataframe['actuals'] = result_dataframe['actuals'].transform(
                lambda x: "{:.2f};{:.2f};{:.2f}".format(x, x, x)
            )
            headers.append('actuals')

        factors = prediction.prediction_result.result['factors']

        percent_factors = calculate_average_factors_percentage(factors)
        context['result'] = {
            'data': prediction.prediction_result.result['datapoints'][0]['prediction'],
            'header': headers,
            'target_feature': target_feature,
            'timestamp_range': [
                result_dataframe.index[0].strftime(DATETIME_FORMAT),
                result_dataframe.index[-1].strftime(DATETIME_FORMAT)
            ],
            'status': prediction.statuses[-1].state,
            'prediction_result': prediction.prediction_result,
            'factors': percent_factors
        }

    return render_template('prediction/view.html', **context)


@customer_blueprint.route('/prediction/<string:task_code>/download')
@requires_access_token
def download_prediction_csv(task_code):
    prediction = PredictionTaskEntity.get_by_task_code(task_code)
    if not prediction:
        return handle_error(404, "No prediction found!")

    if not prediction.company_id == g.user.company_id:
        return handle_error(403, "Unauthorised")

    result_dataframe = prediction_result_to_dataframe_with_error(prediction)

    return Response(
        result_dataframe.to_csv(),
        mimetype='text/csv',
        headers={"Content-disposition": "attachment; filename={}.csv".format(
            prediction.name
        )})


@customer_blueprint.route('/prediction/<string:task_code>/factors')
@requires_access_token
def download_prediction_factors(task_code):
    prediction = PredictionTaskEntity.get_by_task_code(task_code)
    if not prediction:
        return handle_error(404, "No prediction found!")

    if not prediction.company_id == g.user.company_id:
        return handle_error(403, "Unauthorised")

    factors = prediction.prediction_result.result['factors']
    prediction_factors = combine_average_and_symbols_sensitivities(factors)

    df = pd.DataFrame(prediction_factors)
    return Response(
        df.to_csv(index_label=['symbol']),
        mimetype='text/csv',
        headers={"Content-disposition": "attachment; filename={}_sensitivities.csv".format(
            prediction.name
        )})


@customer_blueprint.route('/prediction/predictions/download')
@requires_access_token
def download_all_predictions():

    current_user_company_id = g.user.company_id
    prediction_list = PredictionTaskEntity.get_successful_by_company_id(current_user_company_id)

    result_dataframe = pd.DataFrame()

    for prediction in prediction_list:
        current_df = prediction_result_to_dataframe_with_error(prediction)
        result_dataframe = pd.concat([result_dataframe, current_df])

    return Response(
        result_dataframe.sort_index().to_csv(),
        mimetype='text/csv',
        headers={"Content-disposition": "attachment; filename={}_bulk_predictions.csv".format(
                datetime.now().strftime('%Y%m%d%H%M%S')
        )})


@customer_blueprint.route('/prediction', methods=['GET'])
@requires_access_token
def list_predictions():
    prediction_tasks = services.prediction.get_tasks_by_company_id(g.user.company.id)

    context = {
        'user_id': g.user.id,
        'profile': {'email': g.user.email},
        'datasource': g.user.company.current_datasource,
        'prediction_task_list': prediction_tasks
    }

    return render_template("prediction/list.html", **context)


@customer_blueprint.route('/datasource', methods=['POST'])
@requires_access_token
def datasource_upload():
    user = g.user
    company = user.company

    if not len(request.files):
        logging.debug("No file was uploaded")
        return handle_error(400, "No file Provided!")

app/views/datasource.py
import logging
import os

import pandas as pd
from flask import Blueprint, request, abort, current_app, url_for, g, flash
from werkzeug.utils import secure_filename

from app import services
from app.core.auth import requires_access_token
from app.core.content import ApiResponse
from app.core.models import DataSource
from app.core.utils import allowed_extension, generate_upload_code, handle_error
from app.entities.datasource import UploadTypes

datasource_blueprint = Blueprint('datasource', __name__)


@datasource_blueprint.route('/', methods=['GET'])
@requires_access_token
def list_datasources():
    datasources = g.user.company.data_sources
    response = ApiResponse(
        content_type=request.accept_mimetypes.best,
        context=datasources
    )
    return response()


@datasource_blueprint.route('/current')
@requires_access_token
def current():
    current_datasource = g.user.company.current_datasource
    response = ApiResponse(
        content_type=request.accept_mimetypes.best,
        context=current_datasource,
    )
    return response()


@datasource_blueprint.route('/<string:datasource_id>')
@requires_access_token
def get(datasource_id):
    datasource = services.datasource.get_by_upload_code(datasource_id)
    if not datasource:
        logging.debug(f"No datasource was found for id {datasource_id}")
        abort(404, 'No data source found!')

    response = ApiResponse(
        content_type=request.accept_mimetypes.best,
        context=datasource
    )

    return response()


@datasource_blueprint.route('/', methods=['POST'])
@requires_access_token
def upload():
    user = g.user
    company = user.company
    company_configuration = company.current_configuration

    if not company_configuration:
        return handle_error(400, f"{company.name} cannot upload historical data yet, please contact support.")
    if not len(request.files):
        logging.debug("No file was uploaded")
        return handle_error(400, "No file Provided!")

    uploaded_file = request.files['upload']

    if not allowed_extension(uploaded_file.filename):
        logging.debug(f"Invalid extension for upload {uploaded_file.filename}")
        return handle_error(400, f'File extension for {uploaded_file.filename} not allowed!')

    upload_code = generate_upload_code()
    filename = services.datasource.generate_filename(upload_code, secure_filename(uploaded_file.filename))

    interpreter = services.company.get_datasource_interpreter(company_configuration)
    target_feature = company_configuration.configuration.target_feature
    data_frame, errors = interpreter.from_csv_to_dataframe(uploaded_file)

    if errors:
        logging.debug(f"Invalid file uploaded: {', '.join(errors)}")
        return handle_error(400, ', '.join(errors))

    if not target_feature in list(data_frame.columns):
        return handle_error(400, f"Required feature {target_feature} not in {uploaded_file.filename}")

    features = list(data_frame.columns)

    if user.company.current_datasource:
        data_source = services.datasource.get_by_upload_code(user.company.current_datasource.upload_code)
        existing_data_frame = data_source._model.get_file()
        data_frame = pd.concat([existing_data_frame, data_frame])

    saved_path = os.path.join(current_app.config['UPLOAD_FOLDER'], filename + '.hdf5')
    data_frame = data_frame.reset_index()
    data_frame = data_frame.drop_duplicates()
    data_frame = data_frame.set_index(interpreter.INDEX_COLUMN)
    data_frame = data_frame.sort_index(ascending=True)
    data_frame.to_hdf(saved_path, key=current_app.config['HDF5_STORE_INDEX'])

    original = True if len(company.data_sources) == 0 else False

    upload = DataSource(
        user_id=user.id,
        company_id=company.id,
        upload_code=upload_code,
        type=UploadTypes.FILESYSTEM,
        location=saved_path,
        filename=filename,
        start_date=data_frame.index[0].to_pydatetime(),
        end_date=data_frame.index[-1].to_pydatetime(),
        is_original=original,
        features=', '.join(features),
        target_feature=target_feature,
    )

    datasource = services.datasource.insert(upload)

    upload_strategy_class = company_configuration.configuration.upload_strategy
    upload_strategy = services.strategies.get_upload_strategy(upload_strategy_class)
    upload_strategy.run(datasource=datasource, company_configuration=company_configuration)

    response = ApiResponse(
        content_type=request.accept_mimetypes.best,
        context=datasource,
        next=url_for('customer.list_datasources'),
        status_code=201
    )

    return response()


@datasource_blueprint.route('/delete/<string:datasource_id>', methods=['POST'])
@requires_access_token
def delete(datasource_id):
    datasource = services.datasource.get_by_upload_code(datasource_id)
    if datasource.is_original:
        message = f"Tried to delete original ingestion datasource: {datasource_id}"
        logging.debug(message)
        return handle_error(400, message)

    services.datasource.delete(datasource)

    response = ApiResponse(
        content_type=request.accept_mimetypes.best,
        next=url_for('customer.list_datasources'),
        status_code=200
    )
    flash(f"Historical data version {datasource_id} has been deleted", category='success')
    return response()

app/templates/datasource/confirm.html
{% extends "layout/main.html" %}

{% set page_title %}Update Datasource{% endset %}

{% block page_header %}
    <h1>
        Confirm Historical Data upload
    </h1>
{% endblock %}
{% block breadcrumb_items %}
    {{ super() }}
    <li><a class="active"><i class="fa fa-database"></i> Historical Data confirm</a></li>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-xs-12">
            {% if not current_datasource_dataframe.empty %}
                <div class="box box-primary">
                    <h3 class="box-header with-border">Current historical data preview</h3>
                    <div class="box-body">
                        <div>
                            <p>Last 5 lines of your current historical data. (ascending order)</p>

                            {{ dataframe_to_clean_html(current_datasource_dataframe.tail(5)) }}
                        </div>
                    </div>
                </div>
            {% endif %}
            <div class="box box-success">
                <h3 class="box-header with-border">Your upload</h3>
                <div class="box-body">
                    {%  set preview_lines = 3 %}
                    <div>
                        <h4>First {{ preview_lines }} rows</h4>
                        {{ dataframe_to_clean_html(uploaded_dataframe.head(preview_lines)) }}
                        <h4>Last {{ preview_lines }} rows</h4>
                        {{ dataframe_to_clean_html(uploaded_dataframe.tail(preview_lines)) }}
                    </div>
                    <form action="{{ url_for('customer.datasource_confirm') }}" method="post">
                        <input type="hidden" name="upload_code" value="{{ upload_code }}">
                        <div class="text-center">
                            <p>Please confirm or discard the uploaded data.</p>
                            {% if company_configuration.upload_strategy == 'TrainAndPredictOnUploadStrategy' %}
                                <p>If you confirm the upload, a Prediction task will be automatically triggered</p>
                            {% endif %}
                            <p>
                                <a href="{{ url_for('customer.datasource_discard', upload_code=upload_code) }}"
                                   class="btn btn-danger">Discard</a>
                                &nbsp;&nbsp;&nbsp;
                                <input type="submit" class="btn btn-success" value="Confirm" id="datasource_confirm_button">
                            </p>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block footer_js %}
    {{ super() }}
{% endblock %}

{% macro dataframe_to_clean_html(dataframe) %}
    <div class="datasource-table-container table-responsive no-padding">
        {{ dataframe.to_html(classes='table table-hover datasource-table', index_names=False, border=0)|safe }}
    </div>
{% endmacro %}

app/templates/datasource/index.html
{% extends "layout.html" %}

{% set page_title %}Update Datasource{% endset %}

{% block page_header %}
    <h1>
        Historical Data
        <small>An overview of your historical data</small>
    </h1>
{% endblock %}
{% block breadcrumb_items %}
    {{ super() }}
    <li><a class="active"><i class="fa fa-upload"></i> Upload Datasource</a></li>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-xs-12">
            <div class="box box-primary">
                <div class="box box-success">
                    <h3 class="box-header with-border">Overview</h3>
                    <div class="box-body">

                        {% if current_datasource %}
                            {{ macros.print_datasource_info(current_datasource) }}
                        {% else %}
                            <div class="callout callout-warning">
                                <h4>No datasource set</h4>
                                <p>To use our prediction engine you need a datasource</p>
                            </div>
                        {% endif %}

                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <h3 class="box-header with-border">Update your historical data</h3>
                <div class="box-body">
                    <form action="{{ url_for('datasource.upload') }}" method="post" enctype="multipart/form-data" class="form-inline">
                        <div class="form-group row">
                            <div class="col-xs-10">
                                <div class="input-group">
                                    <input type="text" id="file_path" class="form-control" placeholder="Browse...">
                                    <span class="input-group-btn">
                                    <button class="btn btn-default" type="button" id="file_browser">
                                    <i class="fa fa-search"></i> Browse</button>
                                </span>

                                </div>
                                <input type="file" class="hidden" name="upload" id="upload">
                            </div>
                            <div class="col-xs-2">
                                <input class="btn btn-primary" type="submit" value="Upload file" name="submit">
                            </div>
                        </div>
                    </form>
                    <p class="mt-4">
                        <a href="{{ url_for('static', filename='demo/data_template.csv') }}" target="_blank"><i class="fa fa-download"></i> &nbsp;Download file template</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
     <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <h3 class="box-header with-border">Upload log</h3>
                <div class="box-body">

                    <table class="table table-bordered">
                        <tbody>
                            <tr>
                                <th>filename</th>
                                <th>type</th>
                                <th>start date</th>
                                <th>end date</th>
                                <th>last updated</th>
                                <th></th>
                            </tr>
                          {%  for datasource in datasource_history %}
                            <tr>
                                <td>{{ datasource.filename }}</td>
                                <td>{{ datasource.type.value }}</td>
                                <td>{{ datasource.start_date }}</td>
                                <td>{{ datasource.end_date }}</td>
                                <td>{{ macros.format_datetime(datasource.last_update) }}</td>
                                <td><a href="{{ url_for('datasource.get', datasource_id=datasource.upload_code) }}">
                                    <i class="fa fa-list"></i></a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}



{% block footer_js %}
    {{ super() }}
    <script>
        $('#file_browser').click(function (e) {
            e.preventDefault();
            $('#upload').click();
        });

        $('#upload').change(function () {
            $('#file_path').val($(this).val());
        });

        $('#file_path').click(function () {
            $('#file_browser').click();
        });
    </script>
{% endblock %}

app/templates/datasource/list.html
{% extends "layout/main.html" %}

{% set page_title %}Update Datasource{% endset %}

{% block page_header %}
    <h1>
        Historical Data
        <small>An overview of your historical data</small>
    </h1>
{% endblock %}
{% block breadcrumb_items %}
    {{ super() }}
    <li><a class="active"><i class="fa fa-upload"></i> Upload Datasource</a></li>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-xs-12">
            <div class="box box-primary">
                <h3 class="box-header with-border">Overview</h3>
                <div class="box-body">

                    {% if current_datasource %}
                        {{ macros.print_datasource_info(current_datasource) }}
                        {% if prediction_task_list %}
                            <h4>Predictions associated with this Historical Data Upload</h4>
                            {{ macros.print_datasource_task_list(prediction_task_list) }}
                        {% endif %}
                        <div id="debug-div"></div>
                    {% else %}
                        <p>Your Historical Data is empty</p>
                    {% endif %}

                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <h3 class="box-header with-border">Update your historical data</h3>
                <div class="box-body">
                    <form action="{{ url_for('customer.datasource_upload') }}" method="post"
                          enctype="multipart/form-data" class="form-inline">
                        <div class="form-group row">
                            <div class="col-xs-10">
                                <div class="input-group">
                                    <input type="text" id="file_path" class="form-control" placeholder="Browse...">
                                    <span class="input-group-btn">
                                    <button class="btn btn-default" type="button" id="file_browser">
                                    <i class="fa fa-search"></i> Browse</button>
                                </span>

                                </div>
                                <input type="file" class="hidden" name="upload" id="upload">
                            </div>
                            <div class="col-xs-2">
                                <input class="btn btn-primary" type="submit" value="Upload file"
                                       id="datasource_submit_button" name="submit" disabled>
                            </div>
                        </div>
                    </form>
                    <p class="mt-4">
                        <a href="{{ url_for('customer.get_company_datasource_template') }}" target="_blank"><i
                                class="fa fa-download"></i> &nbsp;Download file template</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
    {% if datasource_history %}
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <h3 class="box-header with-border">Upload log</h3>
                    <div class="box-body">
                        <table class="table table-bordered">
                            <tbody>
                            <tr>
                                <th>filename</th>
                                <th>type</th>
                                <th>start date</th>
                                <th>end date</th>
                                <th>last updated</th>
                                <th></th>
                            </tr>
                            {% for datasource in datasource_history %}
                                <tr>
                                    <td>
                                        <a href="{{ url_for('customer.view_datasource', datasource_id=datasource.upload_code) }}">{{ datasource.filename }}</a>
                                    </td>
                                    <td>{{ datasource.type.value }}</td>
                                    <td>{{ datasource.start_date }}</td>
                                    <td>{{ datasource.end_date }}</td>
                                    <td>{{ macros.format_datetime(datasource.last_update) }}</td>
                                    <td>
                                        <a href="{{ url_for('customer.view_datasource', datasource_id=datasource.upload_code) }}"><i class="fa fa-list"></i></a>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

    {% endif %}
{% endblock %}



{% block footer_js %}
    {{ super() }}
    <script>
        $('#file_browser').click(function (e) {
            e.preventDefault();
            $('#upload').click();
        });

        $('#upload').change(function () {
            file_path = $(this).val();
            $('#file_path').val($(this).val());
            if (file_path) {
                $('#datasource_submit_button').attr('disabled', false)
            } else {
                $('#datasource_submit_button').attr('disabled', true)
            }
        });

        $('#file_path').click(function () {
            $('#file_browser').click();
        });

        $(document).ready(function($){
            setInterval(DatasourceRefresh.refreshTaskCode, 2000)
        })
    </script>
{% endblock %}