app/views/authentication.py
import datetime
import logging

from flask import Blueprint, g, url_for, request

from app import services
from app.core.auth import requires_access_token
from app.core.content import ApiResponse
from app.core.utils import parse_request_data, handle_error
from config import TOKEN_EXPIRATION

authentication_blueprint = Blueprint('authentication', __name__)


@authentication_blueprint.route('/login', methods=['POST'])
@parse_request_data
def login():
    email = g.json.get('email')
    password = g.json.get('password')

    user = services.user.get_by_email(email)
    if not user:
        logging.debug(f"No user found for {email}")
        return handle_error(401, 'Incorrect user or password')

    if not services.user.verify_password(user, password):
        logging.warning(f"Incorrect password for {email}")
        return handle_error(401, 'Incorrect user or password')

    if not user.confirmed:
        logging.warning(f"User {user.email} hasn't been confirmed!")
        return handle_error(401, f'Please confirm user {user.email} first')

    token = services.user.generate_auth_token(user, expiration=TOKEN_EXPIRATION)
    ascii_token = token.decode('ascii')

    response = ApiResponse(
        content_type=request.accept_mimetypes.best,
        next=url_for('customer.dashboard'),
        context={'token': ascii_token}
    )

    response.set_cookie(
        'token', ascii_token,
        expires=datetime.datetime.now() + datetime.timedelta(minutes=TOKEN_EXPIRATION)
    )

    return response()


@authentication_blueprint.route('/logout')
@requires_access_token
def logout():
    response = ApiResponse(
        content_type=request.accept_mimetypes.best,
        next=url_for('main.login')
    )
    response.set_cookie('token', '', expires=0)

    return response()

app/views/customer.py
import logging
import os
from datetime import timedelta, datetime

import pandas as pd
from flask import (
    Blueprint, jsonify, render_template, g, request, abort, Response,
    flash, redirect, url_for, current_app
)

from app import services, ApiResponse
from app.core.auth import requires_access_token
from app.core.models import DataSource
from app.core.utils import handle_error, allowed_extension, generate_upload_code
from app.entities import CompanyConfigurationEntity, PredictionTaskEntity
from app.entities.datasource import UploadTypes
from app.interpreters.prediction import (
    prediction_result_to_dataframe_with_error,
    calculate_average_factors_percentage,
    combine_average_and_symbols_sensitivities)
from config import MAXIMUM_DAYS_FORECAST, DATETIME_FORMAT, DEFAULT_TIME_RESOLUTION

customer_blueprint = Blueprint('customer', __name__)


@customer_blueprint.route('/dashboard')
@requires_access_token
def dashboard():
    company = g.user.company
    prediction_tasks = services.prediction.get_tasks_by_company_id(g.user.company.id)

    context = {
        'user_id': g.user.id,
        'profile': {'email': g.user.email},
        'datasource': company.current_datasource,
        'prediction_task_list': prediction_tasks,
    }

    return render_template('dashboard.html', **context)


@customer_blueprint.route('/datasource', methods=['GET'])
@requires_access_token
def list_datasources():
    company = g.user.company
    current_datasource = company.current_datasource
    prediction_task_list = getattr(current_datasource, 'prediction_task_list', [])

    context = {
        'user_id': g.user.id,
        'profile': {'email': g.user.email},
        'current_datasource': current_datasource,
        'datasource_history': company.data_sources,
        'prediction_task_list': prediction_task_list
    }

    return render_template('datasource/list.html', **context)


@customer_blueprint.route('/datasource/template')
@requires_access_token
def get_company_datasource_template():
    csv_interpreter = services.company.get_datasource_interpreter(g.user.company.current_configuration)
    columns = [csv_interpreter.INDEX_COLUMN] + csv_interpreter.COLUMNS

    return Response(
        pd.DataFrame(columns=columns).to_csv(header=True, index=False),
        mimetype='text/csv',
        headers={"Content-disposition": f"attachment; filename={g.user.company.name}_template.csv"}
    )


@customer_blueprint.route('/datasource/<string:datasource_id>', methods=['GET'])
@requires_access_token
def view_datasource(datasource_id):
    datasource = services.datasource.get_by_upload_code(upload_code=datasource_id)
    if not datasource:
        return handle_error(404, "No such datasource!")
    if not datasource.company_id == g.user.company_id:
        return handle_error(403, "Unauthorised")
    context = {
        'current_datasource': datasource,
        'profile': {'email': g.user.email},
        'prediction_task_list': services.prediction.get_task_for_datasource_id(datasource.id)
    }

    return render_template('datasource/detail.html', **context)


@customer_blueprint.route('/prediction/new', methods=['GET'])
@requires_access_token
def new_prediction():
    company = g.user.company
    current_datasource = company.current_datasource
    if not current_datasource:
        logging.debug(
            f"Asked to create a prediction when no data source was available for company {g.user.company.name}")
        message = f"No data source available. <a href='{url_for('customer.list_datasources')}'>Upload one</a> first!"
        return handle_error(400, message)

    datasource_min_date = current_datasource.end_date
    max_date = datasource_min_date + timedelta(days=MAXIMUM_DAYS_FORECAST)

    context = {
        'user_id': g.user.id,
        'profile': {'email': g.user.email},
        'datasource': current_datasource,
        'datasource_end_date': datasource_min_date,
        'target_feature': company.current_configuration.configuration.target_feature,
        'min_date': datasource_min_date + timedelta(days=1),
        'max_date': max_date
    }

    return render_template('prediction/new.html', **context)


@customer_blueprint.route('/prediction/<string:task_code>')
@requires_access_token
def view_prediction(task_code):
    prediction = services.prediction.get_task_by_code(task_code)
    if not prediction:
        return handle_error(404, "No prediction found!")
    if not prediction.company_id == g.user.company_id:
        return handle_error(403, "Unauthorised")

    datasource = services.datasource.get_by_upload_code(prediction.datasource_upload_code)
    prediction.datasource = datasource

    if prediction.is_completed:
        elapsed = prediction.statuses[-1].last_update - prediction.created_at
    else:
        elapsed = datetime.utcnow() - prediction.created_at

    minutes, seconds = divmod(elapsed.seconds + elapsed.days * 86400, 60)
    hours, minutes = divmod(minutes, 60)

    context = {
        'user_id': g.user.id,
        'profile': {'email': g.user.email},
        'datasource': g.user.company.current_datasource,
        'prediction': prediction,
        'elapsed': f"{hours:02d}:{minutes:02d}:{seconds:02d}",
        'result': None
    }

    result_dataframe = prediction_result_to_dataframe_with_error(prediction)
    if result_dataframe is not None:

        latest_date_in_datasource = g.user.company.current_datasource.end_date.date()
        latest_date_in_results = result_dataframe.index[-1].date()

        headers = list(result_dataframe.columns)
        target_feature = g.user.company.current_configuration.configuration.target_feature

        if latest_date_in_datasource > latest_date_in_results:
            actuals_dataframe = services.datasource.get_dataframe(g.user.company.current_datasource)
            actuals_dataframe.index = actuals_dataframe.index.tz_localize('UTC')
            actuals_dataframe = actuals_dataframe.resample(DEFAULT_TIME_RESOLUTION).sum()
            result_dataframe['actuals'] = actuals_dataframe[target_feature]
            result_dataframe['actuals'] = result_dataframe['actuals'].transform(
                lambda x: "{:.2f};{:.2f};{:.2f}".format(x, x, x)
            )
            headers.append('actuals')

        factors = prediction.prediction_result.result['factors']

        percent_factors = calculate_average_factors_percentage(factors)
        context['result'] = {
            'data': prediction.prediction_result.result['datapoints'][0]['prediction'],
            'header': headers,
            'target_feature': target_feature,
            'timestamp_range': [
                result_dataframe.index[0].strftime(DATETIME_FORMAT),
                result_dataframe.index[-1].strftime(DATETIME_FORMAT)
            ],
            'status': prediction.statuses[-1].state,
            'prediction_result': prediction.prediction_result,
            'factors': percent_factors
        }

    return render_template('prediction/view.html', **context)


@customer_blueprint.route('/prediction/<string:task_code>/download')
@requires_access_token
def download_prediction_csv(task_code):
    prediction = PredictionTaskEntity.get_by_task_code(task_code)
    if not prediction:
        return handle_error(404, "No prediction found!")

    if not prediction.company_id == g.user.company_id:
        return handle_error(403, "Unauthorised")

    result_dataframe = prediction_result_to_dataframe_with_error(prediction)

    return Response(
        result_dataframe.to_csv(),
        mimetype='text/csv',
        headers={"Content-disposition": "attachment; filename={}.csv".format(
            prediction.name
        )})


@customer_blueprint.route('/prediction/<string:task_code>/factors')
@requires_access_token
def download_prediction_factors(task_code):
    prediction = PredictionTaskEntity.get_by_task_code(task_code)
    if not prediction:
        return handle_error(404, "No prediction found!")

    if not prediction.company_id == g.user.company_id:
        return handle_error(403, "Unauthorised")

    factors = prediction.prediction_result.result['factors']
    prediction_factors = combine_average_and_symbols_sensitivities(factors)

    df = pd.DataFrame(prediction_factors)
    return Response(
        df.to_csv(index_label=['symbol']),
        mimetype='text/csv',
        headers={"Content-disposition": "attachment; filename={}_sensitivities.csv".format(
            prediction.name
        )})


@customer_blueprint.route('/prediction/predictions/download')
@requires_access_token
def download_all_predictions():

    current_user_company_id = g.user.company_id
    prediction_list = PredictionTaskEntity.get_successful_by_company_id(current_user_company_id)

    result_dataframe = pd.DataFrame()

    for prediction in prediction_list:
        current_df = prediction_result_to_dataframe_with_error(prediction)
        result_dataframe = pd.concat([result_dataframe, current_df])

    return Response(
        result_dataframe.sort_index().to_csv(),
        mimetype='text/csv',
        headers={"Content-disposition": "attachment; filename={}_bulk_predictions.csv".format(
                datetime.now().strftime('%Y%m%d%H%M%S')
        )})


@customer_blueprint.route('/prediction', methods=['GET'])
@requires_access_token
def list_predictions():
    prediction_tasks = services.prediction.get_tasks_by_company_id(g.user.company.id)

    context = {
        'user_id': g.user.id,
        'profile': {'email': g.user.email},
        'datasource': g.user.company.current_datasource,
        'prediction_task_list': prediction_tasks
    }

    return render_template("prediction/list.html", **context)


@customer_blueprint.route('/datasource', methods=['POST'])
@requires_access_token
def datasource_upload():
    user = g.user
    company = user.company

    if not len(request.files):
        logging.debug("No file was uploaded")
        return handle_error(400, "No file Provided!")

app/templates/401.html
{% extends "layout/main.html" %}
{% block content_header %}{% endblock %}
{% block content %}
    <div class="row aps-error-page">
        <div class="text-center col-md-4 col-md-offset-4">
            <h1 class="headline text-yellow"> 401</h1>
            <div class="error-content">
                <h3><i class="fa fa-warning text-yellow"></i>Unauthorized.</h3>
                <p>
                    {{ message }}
                </p>
                <p>
                    <a href="{{ url_for('customer.dashboard') }}">Return to dashboard</a>
                </p>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/create_task.html
{% extends "layout.html" %}

{% block page_header %}
  <h1>
    New Prediction
    <small>Small info about creating a new prediction</small>
  </h1>
{% endblock %}

{% block breadcrumb_items %}
    {{ super() }}
    <li><a class="active">New Prediction</a></li>
{% endblock %}

{% block content %}
 <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <h3 class="box-header with-border">Data source preview</h3>
                <div class="box-body">
                    [ DATASOURCE PREVIEW ]
                </div>
            </div>
        </div>

         <div class="col-md-12">
            <div class="box box-primary">
                <h3 class="box-header with-border">Submit new prediction</h3>
                <div class="box-body">
                    <form class="form-inline">
                        <div class="form-group">
                            <label for="features">Select features</label>
                            <select name="features"  id="features"  class="selectpicker dropdown-primary" multiple data-live-search="true">
                                <option value="" disabled selected>Select features</option>
                                <option value="1">feature-1</option>
                                <option value="2">feature-2</option>
                                <option value="3">feature-3</option>
                                <option value="4">feature-4</option>
                                <option value="5">feature-5</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="">Start time</label>
                            <div class="input-group date" data-provide="datepicker">
                                <input type="text" class="form-control" name="start_time" >
                                <span class="input-group-addon">
                                    <i class="glyphicon glyphicon-th"></i>
                                </span>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="end_time">End time</label>
                            <div class="input-group date" data-provide="datepicker">
                                <input type="text" class="form-control" name="end_time" id="end_time">
                                <span class="input-group-addon">
                                    <i class="glyphicon glyphicon-th"></i>
                                </span>
                            </div>
                        </div>
                        <div class="form-group">
                            <button type="submit" value="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/dashboard.html
{% extends "layout/main.html" %}

{% block page_title %}Dashboard{% endblock %}

{% block page_header %}
    <h1>
        Overview
        <small>Here's the overview of your status</small>
    </h1>
{% endblock %}
{% block breadcrumb_items %}
    {{ super() }}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <h3 class="box-header with-border">Historical Data</h3>
                <div class="box-body">
                    {% if datasource %}
                        <table class="table table-bordered">
                            <tbody>
                            <tr>
                                <th>filename</th>
                                <th>type</th>
                                <th>start date</th>
                                <th>end date</th>
                                <th>last updated</th>
                                <th>action</th>
                            </tr>
                            <tr>
                                <td>{{ datasource.filename }}</td>
                                <td>{{ datasource.type.value|capitalize }}</td>
                                <td>{{ datasource.start_date }}</td>
                                <td>{{ datasource.end_date }}</td>
                                <td>{{ macros.format_datetime(datasource.last_update) }}</td>
                                <td><a href="{{ url_for('customer.list_datasources') }}"><span
                                        class="fa fa-file"></span></a></td>
                            </tr>
                            </tbody>
                        </table>
                    {% else %}
                        <p>Your Historical Data is empty.</p>
                        <p><a class="btn btn-primary nounderline"
                              href="{{ url_for('customer.list_datasources') }}"><span class="fa fa-upload"></span>
                            create</a></p>
                    {% endif %}
                </div>
            </div>

        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="box box-success">
                <h3 class="box-header with-border">Latest Prediction tasks</h3>
                <div class="box-body">
                    {{ macros.print_task_list(prediction_task_list) }}
                </div>
            </div>
        </div>
    </div>


{% endblock %}

app/templates/datasource_upload.html
{% extends "layout.html" %}

{% set page_title %}Update Datasource{% endset %}

{% block page_header %}
    <h1>
        Update Datasource
        <small>Update your datasource</small>
    </h1>
{% endblock %}
{% block breadcrumb_items %}
    {{ super() }}
    <li><a class="active"><i class="fa fa-upload"></i> Upload Datasource</a></li>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-xs-12">
            <div class="box box-primary">
                <div class="box box-success">
                    <h3 class="box-header with-border">Current Data Source</h3>
                    <div class="box-body">

                        {% if current_datasource %}
                            {{ macros.print_datasource_info(current_datasource) }}
                        {% else %}
                            <div class="callout callout-warning">
                                <h4>No datasource set</h4>
                                <p>To use our prediction engine you need a datasource</p>
                            </div>
                        {% endif %}

                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <h3 class="box-header with-border">Update data source</h3>
                <div class="box-body">
                    <form action="/upload" method="post" enctype="multipart/form-data" class="form-inline">
                        <div class="form-group">
                            <div class="col-xs-10">
                                <div class="input-group">
                                    <input type="text" id="file_path" class="form-control" placeholder="Browse...">
                                    <span class="input-group-btn">
                                    <button class="btn btn-default" type="button" id="file_browser">
                                    <i class="fa fa-search"></i> Browse</button>
                                </span>

                                </div>
                                <input type="file" class="hidden" name="upload" id="upload">
                            </div>
                            <div class="col-xs-2">
                                <input class="btn btn-primary" type="submit" value="Upload file" name="submit">
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}



{% block footer_js %}
    {{ super() }}
    <script>
        $('#file_browser').click(function (e) {
            e.preventDefault();
            $('#upload').click();
        });

        $('#upload').change(function () {
            $('#file_path').val($(this).val());
        });

        $('#file_path').click(function () {
            $('#file_browser').click();
        });
    </script>
{% endblock %}

app/templates/layout.html
<!DOCTYPE html>
<html>
{% include 'partial/html_header.html' %}
{% import 'macros.html' as macros %}
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">
{% include 'partial/main_header.html' %}
{% include 'partial/main_sidebar.html' %}



  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        {% block content_header %}
            {% block page_header %}
                  <h1>
                    Page Header
                    <small>Optional description</small>
                  </h1>
                {% endblock %}
            <ol class="breadcrumb">
                {% block breadcrumb_items %}
                    <li><a href="{{ url_for('customer.dashboard') }}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
                {% endblock %}
            </ol>
        {% endblock %}
    </section>

    <!-- Main content -->
    <section class="content container-fluid">

      {% block content %}{% endblock %}

    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <!-- Main Footer -->
  <footer class="main-footer">
    <!-- To the right -->
    <div class="pull-right hidden-xs">
      Contact Us
    </div>
    <!-- Default to the left -->
    <strong>Copyright &copy; 2018 <a href="#">Alpha-I</a>.</strong> All rights reserved.
  </footer>

</div>

</div>
<!-- ./wrapper -->

{% block footer_js %}
    {%  include 'partial/footer_js.html' %}
    <script>
      $(function () {
        $('input').iCheck({
          checkboxClass: 'icheckbox_square-blue',
          radioClass: 'iradio_square-blue',
          increaseArea: '20%' /* optional */
        });
      });
    </script>
{% endblock %}
</body>
</html>

app/templates/login.html
<!DOCTYPE html>
<html>
{% include 'partial/html_header.html' %}
{% import 'macros.html' as macros %}
<body class="hold-transition login-page">
<div class="login-box">
  <div class="login-logo">
    <b>Alpha-I</b>
      <br/>
    - Prediction Service -
  </div>
  <!-- /.login-logo -->
  <div class="login-box-body">
    <p class="login-box-msg">Please Log In</p>

    <form action="{{ url_for('authentication.login') }}" method="post">
      <div class="form-group has-feedback">
        <input type="email" class="form-control" placeholder="email" name="email">
        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
      </div>
      <div class="form-group has-feedback">
        <input type="password" class="form-control" placeholder="Password" name="password">
        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
      </div>
      <div class="row">
        <div class="col-xs-12">
          <button type="submit" class="btn btn-primary btn-block btn-flat">Sign In</button>
        </div>
        <!-- /.col -->
      </div>
    </form>
  </div>
    <p></p>
     {{ macros.print_flash_messages(dismissible=False) }}
  <!-- /.login-box-body -->
</div>
<!-- /.login-box -->

{%  include 'partial/footer_js.html' %}
<script>
  $(function () {
    $('input').iCheck({
      checkboxClass: 'icheckbox_square-blue',
      radioClass: 'iradio_square-blue',
      increaseArea: '20%' /* optional */
    });
  });
</script>
</body>
</html>

app/templates/macros.html
{% macro format_datetime(datetime) -%}
    {{ datetime.strftime('%Y-%m-%d %H:%M:%S') }}
{%- endmacro %}

{% macro format_date(datetime) -%}
    {{ datetime.strftime('%Y-%m-%d') }}
{%- endmacro %}

{% macro print_datasource_info(datasource) -%}
    <dl class="dl-horizontal">
        <dt>Code</dt>
        <dd>{{ datasource.upload_code }}</dd>

        <dt>Created</dt>
        <dd>{{ format_datetime(datasource.created_at) }}</dd>

        <dt>Type</dt>
        <dd>{{ datasource.type.value|capitalize }}</dd>

        <dt>File</dt>
        <dd>{{ datasource.filename }}</dd>

        <dt>Available features</dt>
        <dd>{{ datasource.features }}</dd>

        <dt>Target feature</dt>
        <dd>{{ datasource.target_feature }}</dd>

        <dt>Start Date</dt>
        <dd>{{ datasource.start_date }}</dd>

        <dt>End Date</dt>
        <dd>{{ datasource.end_date }}</dd>
    </dl>
{%- endmacro %}

{% macro print_datasource_task_list(task_list) %}
    {% if task_list|length > 0 %}
        <table class="table table-bordered" id="datasource-task-list">
            <thead>
            <tr>
                <th>name</th>
                <th>code</th>
                <th>created on</th>
                <th>prediction start</th>
                <th>prediction end</th>
                <th>datasource</th>
                <th>status</th>
                <th></th>
            </tr>
            </thead>
            <tbody>

            {% for task in task_list %}
                <tr class='task-row' id="{{ task.task_code }}" data-completed="{{ task.is_completed }}">
                    <td scope="row"><a
                            href="{{ url_for('customer.view_prediction', task_code=task.task_code) }}">{{ task.name }}</a>
                    </td>
                    <td scope="row">{{ task.task_code }}</td>
                    <td>{{ format_datetime(task.created_at) }}</td>
                    <td>{{ task.prediction_request.start_time }}</td>
                    <td>{{ task.prediction_request.end_time }}</td>
                    <td>
                        <a href="{{ url_for('customer.view_datasource', datasource_id=task.datasource_upload_code) }}">
                            {{ task.datasource_upload_code }}
                        </a>
                    </td>
                    <td><i class="fa {{ get_task_status_icon(task.statuses[-1].state) }}" alt="{{ task.statuses[-1].state }}"/></td>
                    <td><a href="{{ url_for('customer.view_prediction', task_code=task.task_code) }}"><i class="fa fa-list"></i></a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>No tasks found.</p>
    {% endif %}
{% endmacro %}


{% macro get_task_status_icon(status) -%}
    {%- set icon_class = 'fa-refresh fa-spin' -%}
    {% if status == 'SUCCESSFUL' %}
        {%- set icon_class = 'fa-check-circle text-green' -%}
    {%- elif status == 'FAILED' -%}
        {%- set icon_class = 'fa-warning text-yellow' -%}
    {%- endif -%}
    {{ icon_class }}
{%- endmacro -%}

{% macro print_task_list(task_list) %}
    {% if task_list|length > 0 %}
        <table class="table table-bordered">
            <tbody>
            <tr>
                <th>name</th>
                <th>code</th>
                <th>created on</th>
                <th>prediction start</th>
                <th>prediction end</th>
                <th>datasource</th>
                <th>status</th>
                <th></th>
            </tr>
            {% for task in task_list %}
                <tr>
                    <td scope="row"><a
                            href="{{ url_for('customer.view_prediction', task_code=task.task_code) }}">{{ task.name }}</a>
                    </td>
                    <td scope="row">{{ task.task_code }}</td>
                    <td>{{ format_datetime(task.created_at) }}</td>
                    <td>{{ task.prediction_request.start_time }}</td>
                    <td>{{ task.prediction_request.end_time }}</td>
                    <td>
                        <a href="{{ url_for('customer.view_datasource', datasource_id=task.datasource_upload_code) }}">
                            {{ task.datasource_upload_code }}
                        </a>
                    </td>
                    <td><i class="fa {{ get_task_status_icon(task.statuses[-1].state) }}" alt="{{ task.statuses[-1].state }}"/></td>
                    <td><a href="{{ url_for('customer.view_prediction', task_code=task.task_code) }}"><i
                            class="fa fa-list"></i></a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>No tasks found.</p>
    {% endif %}
{% endmacro %}

{% macro print_flash_messages(dismissible=True) %}
{% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    {% for category, message in messages %}
     <div class="alert alert-{{ category|default('info') }} {% if dismissible %}alert-dismissible{% endif %}">
         {%  if dismissible %}<button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>{% endif %}
         <p>{{ message|safe }}</p>
     </div>
    {% endfor %}
  {% endif %}
{% endwith %}
{%  endmacro %}